env:
  folder: development-environment

spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://145.223.22.73:30002/hiringbell_dev
    username: root
    password: live@Bottomhalf_001
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka