env:
  folder: production-environment

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://145.223.22.73:30002/ems_master
    username: root
    password: live@Bottomhalf_001

eureka:
  client:
    enabled: false